pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/OsamaMMedht/CI-CD.git'
            }
        }

        stage('Verify Files') {
            steps {
                dir('Simple-CI-CD') {
                    bat 'dir'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('Simple-CI-CD') {
                    bat 'npm install'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Simple-CI-CD') {
                    bat 'docker build -t node-app .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                dir('Simple-CI-CD') {
                    bat 'docker run -d -p 80:80 --name my-node-app node-app'
                }
            }
        }
    }

    post {
        failure {
            echo 'Build failed.'
        }
        success {
            echo 'Build and run succeeded.'
        }
    }
}
